version: "3"
services:
  app2:
    build:
      context: ./python
      dockerfile: "Dockerfile.dev"
    command: python main.py
    volumes:
      - ../python:/app
      - python-packages:/root/.local/share
volumes:
  python-packages:
